# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.6.0
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: odolbiniyam@gmail.com
author_name: Biniyam Ajaw
cloud_provider: netlify
contract_name: certificate
deployment_language: python
ide_vscode: true
preset_name: production
project_name: CertifyChain
python_linter: ruff
use_dispenser: true
use_github_actions: true
use_python_black: true
use_python_mypy: true
use_python_pip_audit: true
use_python_pytest: true

